name: datagears project

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '>=3.7 <3.9'
        architecture: 'x64'
    
    - name: Install dependencies
      run: pip install poetry && poetry install --dev
    
    - name: Run tests
      run: make test
    