name: datagears project

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    env:
      DASK_SCHEDULER_ADDRESS: scheduler

    # services:
      # Label used to access the service container
      # scheduler:
      #   image: daskdev/dask
      #   ports:
      #     - "8786:8786"
      #     - "8787:8787"
      #   command: ["dask-scheduler"]

      # worker:
      #   image: daskdev/dask
      #   command: ["dask-worker", "tcp://scheduler:8786"]
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: start dask cluster
      run: docker-compose -f dask/docker-compose.yml up -d

    - name: setup python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    
    - name: install system packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y graphviz

    - name: install dependencies
      run: pip install poetry && poetry install
    
    - name: run tests
      run: poetry run make test
    